### ISSUE TITLE
Generator trying to write to missing asset.rb

### ISSUE THREAD

**Issue by joe1chen** [rossta/serviceworker-rails#16]
I'm using a Rails 3 project.  When running 
```
rails g serviceworker:install
```

I get the following error:
```
   append  config/initializers/assets.rb
/Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `binread': No such file or directory @ rb_sysopen - /Users/jc/Development/myapp/config/initializers/assets.rb (Errno::ENOENT)
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `replace!'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:59:in `invoke!'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:30:in `insert_into_file'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:180:in `append_to_file'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/serviceworker-rails-0.4.0/lib/generators/serviceworker/install_generator.rb:29:in `update_precompiled_assets'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/railties-3.2.22.2/lib/rails/generators.rb:171:in `invoke'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/railties-3.2.22.2/lib/rails/commands/generate.rb:12:in `<top (required)>'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
	from /Users/jc/.rvm/gems/ruby-2.3.1@idogo/gems/railties-3.2.22.2/lib/rails/commands.rb:29:in `<top (required)>'
	from script/rails:14:in `require'
	from script/rails:14:in `<main>'
```

I tried to get around this by adding an assets.rb file but then it runs into another error:
```
/Users/jc/Development/myapp/config/initializers/serviceworker.rb:1:in `<top (required)>': undefined method `configure' for #<MyApp::Application:0x007ffd5edfd190> (NoMethodError)
Did you mean?  config
```

**Comment by rossta** [comment]
@joe1chen Thanks for the report. Which version of Rails and Ruby are you using?

**Comment by rossta** [comment]
@joe1chen Could try again against the `rails3_compatability` branch?
