### ISSUE TITLE
generator install error

### ISSUE THREAD

**Issue by heri** [rossta/serviceworker-rails#30]
Hi =

If main layout is `application.haml` or `application.erb`, then `rails g serviceworker:install` throws an error

```
/Users/heri/.rvm/gems/ruby-2.2.3/gems/thor-0.19.4/lib/thor/actions/inject_into_file.rb:95:in `binread': no implicit conversion of nil into String (TypeError)
	from /Users/heri/.rvm/gems/ruby-2.2.3/gems/thor-0.19.4/lib/thor/actions/inject_into_file.rb:95:in `replace!'
	from /Users/heri/.rvm/gems/ruby-2.2.3/gems/thor-0.19.4/lib/thor/actions/inject_into_file.rb:56:in `invoke!'
	from /Users/heri/.rvm/gems/ruby-2.2.3/gems/thor-0.19.4/lib/thor/actions.rb:95:in `action'
	from /Users/heri/.rvm/gems/ruby-2.2.3/gems/thor-0.19.4/lib/thor/actions/inject_into_file.rb:27:in `insert_into_file'
	from /Users/heri/.rvm/gems/ruby-2.2.3/gems/serviceworker-rails-0.5.4/lib/generators/serviceworker/install_generator.rb:36:in `update_application_layout'
```

I had to rename application.haml to make it work

thanks for the gem !

**Comment by rossta** [comment]
Thanks for the report, @heri. I have a fix in progress.

**Comment by heri** [comment]
Thanks @rossta
