### ISSUE TITLE
Putting service worker outside asset pipeline

### ISSUE THREAD

**Issue by theghall** [rossta/serviceworker-rails#58]
Don't know if this an issue with Heroku or with the gem.

In your README there is this note:

NOTE Given that Service Worker operates in a separate browser thread, outside the context of your web pages, you don't want to include serviceworker.js script in your application.js. So if you have a line like require_tree . in your application.js file, you'll either need to move your serviceworker.js to another location or replace require_tree with something more explicit.

So, I created the directory serviceworkers under app/assets and put my service worker there.  This worked in development but not in production on Heroku.  The following error appears in the Heroku log:

Sprockets::Rails::Helper::AssetNotFound (The asset "event-worker.js" is not present in the asset pipeline.)

I wonder if Heroku is ignoring my custom directory, though I did a search and found nothing.

**Comment by theghall** [comment]
Here is what's in my assets.rb:
Rails.application.configure do
  config.assets.precompile += %w[/app/assets/serviceworkers/event-worker.js]
end

Here is what's in my initializer/serviceworker.rb:
Rails.application.configure do
    config.serviceworker.routes.draw do
      match "/event-worker.js"
    end
end

It works in development but when I push it to Heroku, as noted above, I get the following error in my logs:
Sprockets::Rails::Helper::AssetNotFound (The asset "event-worker.js" is not present in the asset pipeline.)

Maybe I can't put my serviceworker in /app/assests/serviceworkers if I use Heroku.

**Comment by theghall** [comment]
I got more detailed log info:
018-08-20T15:48:02.086899+00:00 app[web.1]: I, [2018-08-20T15:48:02.086786 #4]  INFO -- : [ee7191b3-2e70-4adc-a73d-5c4c5f36c9b2] Started GET "/event-worker.js" for 173.61.102.88 at 2018-08-20 15:48:02 +0000
2018-08-20T15:48:02.089034+00:00 app[web.1]: F, [2018-08-20T15:48:02.088916 #4] FATAL -- : [ee7191b3-2e70-4adc-a73d-5c4c5f36c9b2] vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:83:in `compute_asset_path'
2018-08-20T15:48:02.089043+00:00 app[web.1]: [ee7191b3-2e70-4adc-a73d-5c4c5f36c9b2] vendor/bundle/ruby/2.5.0/gems/serviceworker-rails-0.5.5/lib/serviceworker/middleware.rb:29:in `call'
2018-08-20T15:48:02.089047+00:00 app[web.1]: [ee7191b3-2e70-4adc-a73d-5c4c5f36c9b2] vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
2018-08-20T15:48:02.088544+00:00 app[web.1]: F, [2018-08-20T15:48:02.088385 #4] FATAL -- : [ee7191b3-2e70-4adc-a73d-5c4c5f36c9b2]
2018-08-20T15:48:02.089048+00:00 app[web.1]: [ee7191b3-2e70-4adc-a73d-5c4c5f36c9b2] vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
2018-08-20T15:48:02.089052+00:00 app[web.1]: [ee7191b3-2e70-4adc-a73d-5c4c5f36c9b2] vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/etag.rb:25:in `call'
2018-08-20T15:48:02.089056+00:00 app[web.1]: [ee7191b3-2e70-4adc-a73d-5c4c5f36c9b2] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
2018-08-20T15:48:02.089060+00:00 app[web.1]: [ee7191b3-2e70-4adc-a73d-5c4c5f36c9b2] vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:226:in `call'
2018-08-20T15:48:02.089062+00:00 app[web.1]: [ee7191b3-2e70-4adc-a73d-5c4c5f36c9b2] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/cookies.rb:670:in `call'
2018-08-20T15:48:02.089058+00:00 app[web.1]: [ee7191b3-2e70-4adc-a73d-5c4c5f36c9b2] vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:232:in `context'
2018-08-20T15:48:02.088724+00:00 app[web.1]: F, [2018-08-20T15:48:02.088580 #4] FATAL -- : [ee7191b3-2e70-4adc-a73d-5c4c5f36c9b2] Sprockets::Rails::Helper::AssetNotFound (The asset "event-worker.js" is not present in the asset pipeline.):

**Comment by rossta** [comment]
Yes, but what about your Rails configuration? Are you [precompiling the asset](https://github.com/rossta/serviceworker-rails#precompile-the-assets)? Are you setting up a [route for the serviceworker](https://github.com/rossta/serviceworker-rails#configure-the-middleware)?

**Comment by theghall** [comment]
As noted in my second comment I am precompiling the asset and I did set up a route.  And again, this is working in development but not Heroku.  I'm not married to putting my service worker in /app/assets/serviceworkers, but it as I mentioned in my first comment that your Readme noted it  might be a good idea to put it somewhere besides app/assets/javascript.

**Comment by rossta** [comment]
Using `app/assets/serviceworkers` could be the issue. I personally would put the serviceworker under `app/assets/javascripts` and just be sure to exclude it from application.js.

**Comment by theghall** [comment]
Putting my worker in /app/assets/javascripts/serviceworkers worked.  But I am having Uglifier issues now.  Not sure why.  I had to disable it to get things to work.  But that's not your issue.
